"""rename_tables_to_indonesian

Revision ID: f9d871f60f1f
Revises: 016d4819bf5a
Create Date: 2025-04-04 20:29:50.403395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9d871f60f1f'
down_revision = '016d4819bf5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('users', 'pengguna')
    with op.batch_alter_table('pengguna') as batch_op:
        batch_op.alter_column('username', new_column_name='nama_belakang')
        batch_op.alter_column('password_hash', new_column_name='kata_sandi_hash')
        batch_op.alter_column('created_at', new_column_name='dibuat_di')
        batch_op.alter_column('updated_at', new_column_name='diperbarui_di')
    op.rename_table('accounts', 'akun')
    with op.batch_alter_table('akun') as batch_op:
        batch_op.alter_column('account_type', new_column_name='tipe_akun')
        batch_op.alter_column('account_number', new_column_name='nomor_akun')
        batch_op.alter_column('balance', new_column_name='keseimbangan')
        batch_op.alter_column('user_id', new_column_name='pengguna_id')
        batch_op.alter_column('created_at', new_column_name='dibuat_di')
        batch_op.alter_column('updated_at', new_column_name='diperbarui_di')
    op.rename_table('transactions', 'transaksi')
    with op.batch_alter_table('transaksi') as batch_op:
        batch_op.alter_column('amount', new_column_name='jumlah')
        batch_op.alter_column('transaction_type', new_column_name='jenis')
        batch_op.alter_column('description', new_column_name='keterangan')
        batch_op.alter_column('from_account_id', new_column_name='dari_akun_id')
        batch_op.alter_column('to_account_id', new_column_name='ke_akun_id')
        batch_op.alter_column('created_at', new_column_name='dibuat_di')
    # Update foreign key references
    with op.batch_alter_table('akun') as batch_op:
        batch_op.create_foreign_key('fk_akun_pengguna', 'pengguna', ['pengguna_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('pengguna', 'users')
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('nama_belakang', new_column_name='username')
        batch_op.alter_column('kata_sandi_hash', new_column_name='password_hash')
        batch_op.alter_column('dibuat_di', new_column_name='created_at')
        batch_op.alter_column('diperbarui_di', new_column_name='updated_at')
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.rename_table('akun', 'accounts')
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column('tipe_akun', new_column_name='account_type')
        batch_op.alter_column('nomor_akun', new_column_name='account_number')
        batch_op.alter_column('keseimbangan', new_column_name='balance')
        batch_op.alter_column('pengguna_id', new_column_name='user_id')
        batch_op.alter_column('dibuat_di', new_column_name='created_at')
        batch_op.alter_column('diperbarui_di', new_column_name='updated_at')
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('account_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('balance', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='accounts_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('account_number', ['account_number'], unique=True)

    op.rename_table('transaksi', 'transactions')
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.alter_column('jumlah', new_column_name='amount')
        batch_op.alter_column('jenis', new_column_name='transaction_type')
        batch_op.alter_column('keterangan', new_column_name='description')
        batch_op.alter_column('dari_akun_id', new_column_name='from_account_id')
        batch_op.alter_column('ke_akun_id', new_column_name='to_account_id')
        batch_op.alter_column('dibuat_di', new_column_name='created_at')
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('from_account_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_account_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], name='transactions_ibfk_1'),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], name='transactions_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('transaksi')
    op.drop_table('akun')
    op.drop_table('pengguna')
    # ### end Alembic commands ###
